### ISSUE TITLE
examples/studentdesks/studentdesks.py doesn't work with Python 3

### ISSUE THREAD

**Issue by scls19fr** [python-constraint/python-constraint#12]
With Python 2

```bash
$ python examples/studentdesks/studentdesks.py
   A
   E D E D A
   C B C B
   E D E D
 A C B C B
         A
```

but with Python 3

```bash
$ python examples/studentdesks/studentdesks.py
Traceback (most recent call last):
  File "examples/studentdesks/studentdesks.py", line 47, in <module>
    main()
  File "examples/studentdesks/studentdesks.py", line 35, in main
    solutions = solve()
  File "examples/studentdesks/studentdesks.py", line 30, in solve
    solutions = problem.getSolution()
  File "/Users/scls/github/python-constraint/constraint/__init__.py", line 228, in getSolution
    return self._solver.getSolution(domains, constraints, vconstraints)
  File "/Users/scls/github/python-constraint/constraint/__init__.py", line 537, in getSolution
    return iter.next()
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by scls19fr** [comment]
Moreover, in this example 

    for row in range(len(STUDENTDESKS) - 1):
        for col in range(len(STUDENTDESKS[row]) - 1):

should use `enumerate`
