### ISSUE TITLE
examples/wordmath/seisseisdoze.py doesn't work with Python 3

### ISSUE THREAD

**Issue by s-celles** [python-constraint/python-constraint#13]
```
python examples/wordmath/seisseisdoze.py
SEIS+SEIS=DOZE
%(s)d%(e)d%(i)d%(s)s+%(s)d%(e)d%(i)d%(s)d=%(d)d%(o)d%(z)d%(e)d
Traceback (most recent call last):
  File "examples/wordmath/seisseisdoze.py", line 38, in <module>
    main()
  File "examples/wordmath/seisseisdoze.py", line 35, in main
    "%(d)d%(o)d%(z)d%(e)d") % s
TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'
```

but with Python 2

```
$ python examples/wordmath/seisseisdoze.py
SEIS+SEIS=DOZE
4854+4854=9708
4864+4864=9728
4814+4814=9628
3643+3643=7286
```

**Comment by fjwillemsen** [comment]
Wasn't expecting to still happen upon python 2 compatibility issues in 2025, but here we are. I've fixed it now!
