### ISSUE TITLE
MinConflictsSolver use of .keys() on dict broken in Python 3

### ISSUE THREAD

**Issue by mattkindy-praetorian** [python-constraint/python-constraint#39]
Example:
```
from constraint import Problem, MinConflictsSolver

problem = Problem(MinConflictsSolver())
problem.addVariable("x", [0, 1])
problem.addVariable("y", [0, 1])
solution = problem.getSolution()
```
results in 
```
Traceback (most recent call last):
  File "create_project_groupings.py", line 6, in <module>
    solutions = problem.getSolution()
  File "/usr/local/lib/python3.6/site-packages/constraint/__init__.py", line 231, in getSolution
    return self._solver.getSolution(domains, constraints, vconstraints)
  File "/usr/local/lib/python3.6/site-packages/constraint/__init__.py", line 692, in getSolution
    random.shuffle(lst)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 275, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'dict_keys' object does not support indexing
```

This seems like it can be resolved by use of `lst = list(domains.keys())` in line 691 of `constraint/__init__.py`. In the other PR related to this issue, there was concern mentioned about memory usage of the list, but `random.shuffle` realises the full list regardless.

**Comment by scls19fr** [comment]
Thank @mattkindy-praetorian for reporting this issue
I noticed your PR https://github.com/python-constraint/python-constraint/pull/38
but you closed it.
Ideally PR should have a unit test to show what problem it's solving
