### ISSUE TITLE
Install fails: SyntaxError: multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by hansfbaier** [python-constraint/python-constraint#75]
```
$ pip3 install constraint
Defaulting to user installation because normal site-packages is not writeable
Collecting constraint
  Using cached constraint-0.4.1.tar.gz (48 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2gbf7hwm/constraint_ab982014344c4272a250612514a9e3ce/setup.py", line 143
          except OSError, ex:
                 ^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Using Ubuntu 22.04.02 LTS
and python 3.10.

**Comment by hansfbaier** [comment]
Ah, problem solved, the package name is python-constraint.
