### ISSUE TITLE
TypeError: Domains must be instances of subclasses of the Domain class

### ISSUE THREAD

**Issue by scls19fr** [python-constraint/python-constraint#8]
Running tests with Python 2 works fine

    (py2)pc:python-constraint scls$ source activate py2
    discarding //anaconda/envs/py2/bin from PATH
    prepending //anaconda/envs/py2/bin to PATH
    (py2)pc:python-constraint scls$ python --version
    Python 2.7.10 :: Anaconda 2.3.0 (x86_64)
    (py2)pc:python-constraint scls$ nosetests -s -v
    test_constraint.test_abc ... ok
    test_constraint.test_coins ... ok
    test_constraint.test_einstein ... ok
    test_constraint.test_rooks ... ok

    ----------------------------------------------------------------------
    Ran 4 tests in 4.640s

    OK

but not with Python 3

    (py2)pc:python-constraint scls$ source deactivate
    discarding //anaconda/envs/py2/bin from PATH
    pc:python-constraint scls$ python --version
    Python 3.4.3 :: Anaconda 2.3.0 (x86_64)
    pc:python-constraint scls$ nosetests -s -v
    test_constraint.test_abc ... ERROR
    test_constraint.test_coins ... ERROR
    test_constraint.test_einstein ... ok
    test_constraint.test_rooks ... ERROR

    ======================================================================
    ERROR: test_constraint.test_abc
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "//anaconda/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Users/scls/github/python-constraint/tests/test_constraint.py", line 15, in test_abc
        solutions = abc.solve()
      File "/Users/scls/github/python-constraint/examples/abc/abc.py", line 15, in solve
        problem.addVariables("abc", range(1,10))
      File "/Users/scls/github/python-constraint/constraint/__init__.py", line 172, in addVariables
        self.addVariable(variable, domain)
      File "/Users/scls/github/python-constraint/constraint/__init__.py", line 144, in addVariable
        raise TypeError("Domains must be instances of subclasses of "\
    TypeError: Domains must be instances of subclasses of the Domain class

    ======================================================================
    ERROR: test_constraint.test_coins
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "//anaconda/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Users/scls/github/python-constraint/tests/test_constraint.py", line 21, in test_coins
        solutions = coins.solve()
      File "/Users/scls/github/python-constraint/examples/coins/coins.py", line 18, in solve
        problem.addVariable(variable, range(int(total/value)))
      File "/Users/scls/github/python-constraint/constraint/__init__.py", line 144, in addVariable
        raise TypeError("Domains must be instances of subclasses of "\
    TypeError: Domains must be instances of subclasses of the Domain class

    ======================================================================
    ERROR: test_constraint.test_rooks
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "//anaconda/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Users/scls/github/python-constraint/tests/test_constraint.py", line 59, in test_rooks
        solutions = rooks.solve(size)
      File "/Users/scls/github/python-constraint/examples/rooks/rooks.py", line 14, in solve
        problem.addVariables(cols, rows)
      File "/Users/scls/github/python-constraint/constraint/__init__.py", line 172, in addVariables
        self.addVariable(variable, domain)
      File "/Users/scls/github/python-constraint/constraint/__init__.py", line 144, in addVariable
        raise TypeError("Domains must be instances of subclasses of "\
    TypeError: Domains must be instances of subclasses of the Domain class

    ----------------------------------------------------------------------
    Ran 4 tests in 0.198s

    FAILED (errors=3)

I think most trivial problem with Python 3 are solved, but this issue is still alive and I can't see how to fix it.

PS: I'm using Anaconda Python with default Python interpreter being Python 3

**Comment by scls19fr** [comment]
Pinging @niemeyer (original author of python-constraint) http://niemeyer.net/python-constraint

@mbutterick https://github.com/mbutterick/csp
@ac0x https://github.com/ac0x/python-constraint
@cfobel https://github.com/cfobel/python___labix_constraint

There is now in this repository unit tests and continuous integration to help to maintain this package.
Feel free to help but submitting pull requests

**Comment by niemeyer** [comment]
Hi everyone,

Very happy to see you're moving this project forward and providing a proper place for people to collaborate. Great job, thank you.

**Comment by scls19fr** [comment]
My pleasure.

@niemeyer you have been invite in python-constraint GitHub organization (you need to accept this invite)
I have grant you (of course!) owner rights.
